[package]
name = "gbrs-sdl2"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
gbrs = { path = "../gbrs" }
sdl2 = "0.34"
enumset = { version = "1", features = ["serde"] }
anyhow = "1.0.93"
